# measurement/afd_entry_dates.R
#
# Reads the AfD-entry-dates table generated by measurement/afd_entry_dates.py
# (DATA_ROOT/processed/afd_entry_dates.csv, 16 rows: state, entry_date).
# Read once and reuse via a join — do not re-derive entry dates independently
# in R, since that logic already exists (and is validated) in Python, see
# analysis/nsc_analysis.ipynb's AFD_PRESENCE and measurement/afd_entry_dates.py.
#
# Usage:
#   source("measurement/afd_entry_dates.R")
#   df <- df |> dplyr::left_join(load_afd_entry_dates(), by = "state")

load_afd_entry_dates <- function(data_root = Sys.getenv("DATA_ROOT")) {
  path <- file.path(data_root, "processed", "afd_entry_dates.csv")
  if (!file.exists(path)) {
    stop(
      "afd_entry_dates.csv not found at ", path,
      " - run `norm_env/bin/python measurement/afd_entry_dates.py` first."
    )
  }
  readr::read_csv(
    path,
    col_types = readr::cols(
      state = readr::col_character(),
      entry_date = readr::col_date()
    )
  )
}
